const foodData = [
    { name: 'Apple', isSafe: true },
    { name: 'Banana', isSafe: true },
    { name: 'Blueberries', isSafe: true },
    { name: 'Strawberries', isSafe: true },
    { name: 'Raspberries', isSafe: true },
    { name: 'Blackberries', isSafe: true },
    { name: 'Cantaloupe', isSafe: true },
    { name: 'Watermelon', isSafe: true },
    { name: 'Peaches', isSafe: true },
    { name: 'Pears', isSafe: true },
    { name: 'Pineapple', isSafe: true },
    { name: 'Mango', isSafe: true },
    { name: 'Kiwi', isSafe: true },
    { name: 'Oranges', isSafe: true },
    { name: 'Tangerines', isSafe: true },
    { name: 'Papaya', isSafe: true },
    { name: 'Pumpkin', isSafe: true },
    { name: 'Sweet Potatoes (Cooked)', isSafe: true },
    { name: 'Potatoes (Cooked)', isSafe: true },
    { name: 'Carrots', isSafe: true },
    { name: 'Green Beans', isSafe: true },
    { name: 'Cucumber', isSafe: true },
    { name: 'Zucchini', isSafe: true },
    { name: 'Spinach', isSafe: true },
    { name: 'Kale', isSafe: true },
    { name: 'Broccoli', isSafe: true },
    { name: 'Cauliflower', isSafe: true },
    { name: 'Brussels Sprouts', isSafe: true },
    { name: 'Celery', isSafe: true },
    { name: 'Bell Peppers', isSafe: true },
    { name: 'Peas', isSafe: true },
    { name: 'Lettuce', isSafe: true },
    { name: 'Squash', isSafe: true },
    { name: 'Applesauce (unsweetened)', isSafe: true },
    { name: 'Yogurt (plain)', isSafe: true },
    { name: 'Cheese (moderate amounts of specific cheeses)', isSafe: true },
    { name: 'Cottage Cheese (moderate amounts)', isSafe: true },
    { name: 'Eggs', isSafe: true },
    { name: 'Chicken', isSafe: true },
    { name: 'Turkey', isSafe: true },
    { name: 'Beef', isSafe: true },
    { name: 'Lamb', isSafe: true },
    { name: 'Duck', isSafe: true },
    { name: 'Salmon', isSafe: true },
    { name: 'Tuna', isSafe: true },
    { name: 'Trout', isSafe: true },
    { name: 'Whitefish', isSafe: true },
    { name: 'Cod', isSafe: true },
    { name: 'Shrimp', isSafe: true },
    { name: 'Crab', isSafe: true },
    { name: 'Oatmeal', isSafe: true },
    { name: 'Rice', isSafe: true },
    { name: 'Quinoa', isSafe: true },
    { name: 'Barley', isSafe: true },
    { name: 'Pumpkin Seeds', isSafe: true },
    { name: 'Sunflower Seeds', isSafe: true },
    { name: 'Peanut Butter (unsweetened)', isSafe: true },
    { name: 'Almond Butter', isSafe: true },
    { name: 'Cashew Butter', isSafe: true },
    { name: 'Flaxseed', isSafe: true },
    { name: 'Chia Seeds', isSafe: true },
    { name: 'Coconut (unsweetened)', isSafe: true },
    { name: 'Coconut Oil', isSafe: true },
    { name: 'Olive Oil', isSafe: true },
    { name: 'Honey', isSafe: true },
    { name: 'Cranberries', isSafe: true },
    { name: 'Cranberry Sauce (unsweetened)', isSafe: true },
    { name: 'Nectarines', isSafe: true },
    { name: 'Apricots', isSafe: true },
    { name: 'Cherries (pitted)', isSafe: true },
    { name: 'Figs (fresh)', isSafe: true },
    { name: 'Dates (fresh)', isSafe: true },
    { name: 'Persimmons', isSafe: true },
    { name: 'Guava', isSafe: true },
    { name: 'Lychee', isSafe: true },
    { name: 'Dragon Fruit', isSafe: true },
    { name: 'Passion Fruit', isSafe: true },
    { name: 'Pomegranate Seeds', isSafe: true },
    { name: 'Starfruit', isSafe: true },
    { name: 'Durian', isSafe: true },
    { name: 'Jicama', isSafe: true },
    { name: 'Parsnips', isSafe: true },
    { name: 'Turnips', isSafe: true },
    { name: 'Beets', isSafe: true },
    { name: 'Artichokes', isSafe: true },
    { name: 'Asparagus', isSafe: true },
    { name: 'Eggplant', isSafe: true },
    { name: 'Okra', isSafe: true },
    { name: 'Radishes', isSafe: true },
    { name: 'Fennel', isSafe: true },
    { name: 'Water Chestnuts', isSafe: true },
    { name: 'Cheddar Cheese (in moderation)', isSafe: true },
    { name: 'Mozzarella Cheese (in moderation)', isSafe: true },
    { name: 'Parmesan Cheese (in moderation)', isSafe: true },
    { name: 'Swiss Cheese (in moderation)', isSafe: true },
    { name: 'Swiss Chard', isSafe: true },
    { name: 'Mozzarella', isSafe: true },
    { name: 'Arugula', isSafe: true },
    { name: 'Collard Greens', isSafe: true },
    { name: 'Mustard Greens', isSafe: true },
    { name: 'Peaches (fresh)', isSafe: true },
    { name: 'Plums (fresh)', isSafe: true },
    { name: 'Cantaloupe (fresh)', isSafe: true },
    { name: 'Grapefruit', isSafe: true },
    { name: 'Rutabaga', isSafe: true },
    { name: 'Napa Cabbage', isSafe: true },
    { name: 'Butternut Squash', isSafe: true },
    { name: 'Acorn Squash', isSafe: true },
    { name: 'Spaghetti Squash', isSafe: true },
    { name: 'Coconut Meat', isSafe: true },
    { name: 'Mango (fresh)', isSafe: true },
    { name: 'Lychee (fresh)', isSafe: true },
    { name: 'Kumquat', isSafe: true },
    { name: 'Clementine', isSafe: true },
    { name: 'Boysenberries', isSafe: true },
    { name: 'Gooseberries', isSafe: true },
    { name: 'Mulberries', isSafe: true },
    { name: 'Cloudberries', isSafe: true },
    { name: 'Huckleberries', isSafe: true },
    { name: 'Salmonberries', isSafe: true },
    { name: 'Lingonberries', isSafe: true },
    { name: 'Pine Nuts', isSafe: true },
    { name: 'Hemp Seeds', isSafe: true },
    { name: 'Watermelon (seedless)', isSafe: true },
    { name: 'Passionfruit', isSafe: true },
    { name: 'Celeriac', isSafe: true },
    { name: 'Chayote', isSafe: true },
    { name: 'Jackfruit', isSafe: true },
    { name: 'Tamarind', isSafe: true },
    { name: 'Horned Melon', isSafe: true },
    { name: 'Quince', isSafe: true },
    { name: 'Sapodilla', isSafe: true },
    { name: 'Soursop', isSafe: true },
    { name: 'Breadfruit', isSafe: true },
    { name: 'Longan', isSafe: true },
    { name: 'Mung Beans', isSafe: true },
    { name: 'Adzuki Beans', isSafe: true },
    { name: 'Navy Beans', isSafe: true },
    { name: 'Lima Beans', isSafe: true },
    { name: 'Fava Beans', isSafe: true },
    { name: 'Black Beans', isSafe: true },
    { name: 'Kidney Beans', isSafe: true },
    { name: 'Chickpeas', isSafe: true },
    { name: 'Lentils', isSafe: true },
    { name: 'Split Peas', isSafe: true },
    { name: 'Butter Beans', isSafe: true },
    { name: 'Garbanzo Beans', isSafe: true },
    { name: 'Pigeon Peas', isSafe: true },
    { name: 'Cannellini Beans', isSafe: true },
    { name: 'Soybeans', isSafe: true },
    { name: 'Edamame', isSafe: true },
    { name: 'Tempeh', isSafe: true },
    { name: 'Tofu', isSafe: true },
    { name: 'Bamboo Shoots', isSafe: true },
    { name: 'Sprouts', isSafe: true },
    { name: 'Microgreens', isSafe: true },
    { name: 'Alfalfa', isSafe: true },
    { name: 'Cilantro', isSafe: true },
    { name: 'Parsley', isSafe: true },
    { name: 'Basil', isSafe: true },
    { name: 'Mint', isSafe: true },
    { name: 'Thyme', isSafe: true },
    { name: 'Rosemary', isSafe: true },
    { name: 'Oregano', isSafe: true },
    { name: 'Sage', isSafe: true },
    { name: 'Tarragon', isSafe: true },
    { name: 'Dill', isSafe: true },
    { name: 'Chives', isSafe: true },
    { name: 'Garlic (in small amounts)', isSafe: true },
    { name: 'Leeks', isSafe: true },
    { name: 'Shallots', isSafe: true },
    { name: 'Green Onions', isSafe: true },
    { name: 'Beet Greens', isSafe: true },
    { name: 'Turnip Greens', isSafe: true },
    { name: 'Radish Greens', isSafe: true },
    { name: 'Dandelion Greens', isSafe: true },
    { name: 'Purslane', isSafe: true },
    { name: 'Chicory', isSafe: true },
    { name: 'Endive', isSafe: true },
    { name: 'Frisée', isSafe: true },
    { name: 'Escarole', isSafe: true },
    { name: 'Romaine Lettuce', isSafe: true },
    { name: 'Butter Lettuce', isSafe: true },
    { name: 'Iceberg Lettuce', isSafe: true },
    { name: 'Boston Lettuce', isSafe: true },
    { name: 'Radicchio', isSafe: true },
    { name: 'Sunchokes', isSafe: true },
    { name: 'Taro', isSafe: true },
    { name: 'Yams', isSafe: true },
    { name: 'Jerusalem Artichokes', isSafe: true },
    { name: 'Yucca', isSafe: true },
    { name: 'Jalapeno Peppers', isSafe: true },
    { name: 'Habanero Peppers', isSafe: true },
    { name: 'Poblano Peppers', isSafe: true },
    { name: 'Anaheim Peppers', isSafe: true },
    { name: 'Serrano Peppers', isSafe: true },
    { name: 'Cranberry Beans', isSafe: true },
    { name: 'Pole Beans', isSafe: true },
    { name: 'Snap Beans', isSafe: true },
    { name: 'Runner Beans', isSafe: true },
    { name: 'Broad Beans', isSafe: true },
    { name: 'Scarlet Runner Beans', isSafe: true },
    { name: 'Wax Beans', isSafe: true },
    { name: 'Chinese Long Beans', isSafe: true },
    { name: 'Asparagus Beans', isSafe: true },
    { name: 'Yardlong Beans', isSafe: true },
    { name: 'Pinto Beans', isSafe: true },
    { name: 'Black-Eyed Peas', isSafe: true },
    { name: 'Yellow Peas', isSafe: true },
    { name: 'Green Peas', isSafe: true },
    { name: 'Tepary Beans', isSafe: true },
    { name: 'Red Beans', isSafe: true },
    { name: 'White Beans', isSafe: true },
    { name: 'Pink Beans', isSafe: true },
    { name: 'Calypso Beans', isSafe: true },
    { name: 'Christmas Lima Beans', isSafe: true },
    { name: 'Italian Flat Beans', isSafe: true },
    { name: 'Dragon Tongue Beans', isSafe: true },
    { name: 'Rattlesnake Beans', isSafe: true },
    { name: 'Tongue of Fire Beans', isSafe: true },
    { name: 'Royal Burgundy Beans', isSafe: true },
    { name: 'Blue Lake Beans', isSafe: true },
    { name: 'Borlotti Beans', isSafe: true },
    { name: 'Boulder Beans', isSafe: true },
    { name: 'Chocolate', isSafe: false },
    { name: 'Grapes', isSafe: false },
    { name: 'Raisins', isSafe: false },
    { name: 'Avocado', isSafe: false },
    { name: 'Onions', isSafe: false },
    { name: 'Garlic', isSafe: false },
    { name: 'Macadamia Nuts', isSafe: false },
    { name: 'Walnuts', isSafe: false },
    { name: 'Pecans', isSafe: false },
    { name: 'Almonds', isSafe: false },
    { name: 'Alcohol', isSafe: false },
    { name: 'Coffee', isSafe: false },
    { name: 'Tea', isSafe: false },
    { name: 'Caffeine', isSafe: false },
    { name: 'Raw Yeast Dough', isSafe: false },
    { name: 'Xylitol', isSafe: false },
    { name: 'Salt', isSafe: false },
    { name: 'Fatty Foods', isSafe: false },
    { name: 'Bones (cooked)', isSafe: false },
    { name: 'Corn on the Cob', isSafe: false },
    { name: 'Mushrooms (wild)', isSafe: false },
    { name: 'Nutmeg', isSafe: false },
    { name: 'Raw Eggs', isSafe: false },
    { name: 'Raw Meat', isSafe: false },
    { name: 'Raw Fish', isSafe: false },
    { name: 'Candy', isSafe: false },
    { name: 'Gum', isSafe: false },
    { name: 'Fat Trimmings', isSafe: false },
    { name: 'Spoiled Food', isSafe: false },
    { name: 'Cooked Bones', isSafe: false },
    { name: 'Large Amounts of Dairy Products', isSafe: false },
    { name: 'High-Sodium Foods', isSafe: false },
    { name: 'Sugary Foods', isSafe: false },
    { name: 'Citrus Fruits (large amounts)', isSafe: false },
    { name: 'Apple Seeds', isSafe: false },
    { name: 'Cherry Pits', isSafe: false },
    { name: 'Peach Pits', isSafe: false },
    { name: 'Plum Pits', isSafe: false },
    { name: 'Persimmon Seeds', isSafe: false },
    { name: 'Rhubarb Leaves', isSafe: false },
    { name: 'Tomato Leaves and Stems', isSafe: false },
    { name: 'Potato Leaves and Stems', isSafe: false },
    { name: 'Artificial Sweeteners', isSafe: false },
    { name: 'Blue Cheese', isSafe: false },
    { name: 'Green Tomatoes', isSafe: false },
    { name: 'Unripe Potatoes', isSafe: false },
    { name: 'Wild Cherry', isSafe: false },
    { name: 'Poppy Seeds', isSafe: false },
    { name: 'Mustard Seeds', isSafe: false },
    { name: 'Hops', isSafe: false },
    { name: 'Raw Honey', isSafe: false },
    { name: 'Black Walnuts', isSafe: false },
    { name: 'Stone Fruit Pits', isSafe: false },
    { name: 'Coconut Oil (large amounts)', isSafe: false },
    { name: 'Baking Powder', isSafe: false },
    { name: 'Baking Soda', isSafe: false },
    { name: 'Spices (like garlic powder, onion powder, etc.)', isSafe: false },
    { name: 'Energy Drinks', isSafe: false },
    { name: 'Human Medications', isSafe: false },
    { name: 'Vitamin D Supplements', isSafe: false },
    { name: 'Iron Supplements', isSafe: false },
    { name: 'Pain Relievers (like aspirin, ibuprofen, acetaminophen)', isSafe: false },
    { name: 'Mothballs', isSafe: false },
    { name: 'Detergents', isSafe: false },
    { name: 'Fabric Softener Sheets', isSafe: false },
    { name: 'Antifreeze', isSafe: false },
    { name: 'Rodent Poison', isSafe: false },
    { name: 'Insecticides', isSafe: false },
    { name: 'Weed Killers', isSafe: false },
    { name: 'De-Icing Salts', isSafe: false },
    { name: 'Household Cleaners', isSafe: false },
    { name: 'Certain Houseplants', isSafe: false },
    { name: 'Sugar-Free Candies', isSafe: false },
    { name: 'Marijuana', isSafe: false },
    { name: 'Canned Beans', isSafe: false },
    { name: 'Baked Beans', isSafe: false },
    { name: 'Refried Beans', isSafe: false },
    { name: 'Raw Beans', isSafe: false }
];

const ingredientData = [
    { name: 'Sugar', isSafe: false },
    { name: 'Xylitol', isSafe: false },
    { name: 'Chocolate', isSafe: false },
    { name: 'Caffeine', isSafe: false },
    { name: 'Alcohol', isSafe: false },
    { name: 'Onions', isSafe: false },
    { name: 'Garlic', isSafe: false },
    { name: 'Grapes', isSafe: false },
    { name: 'Raisins', isSafe: false },
    { name: 'Macadamia Nuts', isSafe: false },
    { name: 'Avocado', isSafe: false },
    { name: 'Mushrooms', isSafe: false },
    { name: 'Yeast Dough', isSafe: false },
    { name: 'Raw Eggs', isSafe: false },
    { name: 'Raw Meat', isSafe: false },
    { name: 'Bones', isSafe: false },
    { name: 'Milk', isSafe: false },
    { name: 'Salt', isSafe: false },
    { name: 'Sodium Nitrate', isSafe: false },
    { name: 'Sodium Nitrite', isSafe: false },
    { name: 'Fat Trimmings', isSafe: false },
    { name: 'Cooked Bones', isSafe: false },
    { name: 'Peach Pits', isSafe: false },
    { name: 'Plum Pits', isSafe: false },
    { name: 'Cherry Pits', isSafe: false },
    { name: 'Apple Seeds', isSafe: false },
    { name: 'Cinnamon', isSafe: false },
    { name: 'Nutmeg', isSafe: false },
    { name: 'Mustard Seeds', isSafe: false },
    { name: 'Curry Powder', isSafe: false },
    { name: 'Hot Spices', isSafe: false },
    { name: 'Salt Substitutes', isSafe: false },
    { name: 'Moldy Food', isSafe: false },
    { name: 'Citrus Oil Extracts', isSafe: false },
    { name: 'Cocoa Powder', isSafe: false },
    { name: 'Baking Powder', isSafe: false },
    { name: 'Baking Soda', isSafe: false },
    { name: 'Vinegar', isSafe: false },
    { name: 'Potato Leaves', isSafe: false },
    { name: 'Tomato Leaves', isSafe: false },
    { name: 'Rhubarb Leaves', isSafe: false },
    { name: 'Raw Potatoes', isSafe: false },
    { name: 'Green Tomatoes', isSafe: false },
    { name: 'Chives', isSafe: false },
    { name: 'Poppy Seeds', isSafe: false },
    { name: 'Persimmons', isSafe: false },
    { name: 'Pears', isSafe: false },
    { name: 'Peanuts', isSafe: false },
    { name: 'Walnuts', isSafe: false },
    { name: 'Almonds', isSafe: false },
    { name: 'Cashews', isSafe: false },
    { name: 'Pecans', isSafe: false },
    { name: 'Sunflower Seeds', isSafe: false },
    { name: 'Pistachios', isSafe: false },
    { name: 'Soy', isSafe: false },
    { name: 'Tofu', isSafe: false },
    { name: 'Liver', isSafe: false },
    { name: 'Broccoli', isSafe: false },
    { name: 'Coffee', isSafe: false },
    { name: 'Tea', isSafe: false },
    { name: 'Energy Drinks', isSafe: false },
    { name: 'Soda', isSafe: false },
    { name: 'High-Fat Foods', isSafe: false },
    { name: 'Spicy Foods', isSafe: false },
    { name: 'Human Vitamins', isSafe: false },
    { name: 'Raw Fish', isSafe: false },
    { name: 'Cooked Fish Bones', isSafe: false },
    { name: 'Ham', isSafe: false },
    { name: 'Bacon', isSafe: false },
    { name: 'Sausage', isSafe: false },
    { name: 'Corn Cobs', isSafe: false },
    { name: 'Pickles', isSafe: false },
    { name: 'Jalapenos', isSafe: false },
    { name: 'Habaneros', isSafe: false },
    { name: 'Chili Peppers', isSafe: false },
    { name: 'Hot Sauce', isSafe: false },
    { name: 'Gorgonzola', isSafe: false },
    { name: 'Brie', isSafe: false },
    { name: 'Camembert', isSafe: false },
    { name: 'Stilton', isSafe: false },
    { name: 'Brussels Sprouts', isSafe: false },
    { name: 'Kale', isSafe: false },
    { name: 'Spinach', isSafe: false },
    { name: 'Lettuce', isSafe: false },
    { name: 'Celery', isSafe: false },
    { name: 'Cabbage', isSafe: false },
    { name: 'Carrots', isSafe: false },
    { name: 'Beets', isSafe: false },
    { name: 'Radishes', isSafe: false },
    { name: 'Turnips', isSafe: false },
    { name: 'Collard Greens', isSafe: false },
    { name: 'Mustard Greens', isSafe: false },
    { name: 'Arugula', isSafe: false },
    { name: 'Endive', isSafe: false },
    { name: 'Escarole', isSafe: false },
    { name: 'Dandelion Greens', isSafe: false },
    { name: 'Bok Choy', isSafe: false },
    { name: 'Cream Cheese', isSafe: false },
    { name: 'Watercress', isSafe: false },
    { name: 'Swiss Chard', isSafe: false },
    { name: 'Rapini', isSafe: false },
    { name: 'Horseradish', isSafe: false },
    { name: 'Wasabi', isSafe: false },
    { name: 'Cilantro', isSafe: false },
    { name: 'Parsley', isSafe: false },
    { name: 'Basil', isSafe: false },
    { name: 'Mint', isSafe: false },
    { name: 'Rosemary', isSafe: false },
    { name: 'Thyme', isSafe: false },
    { name: 'Oregano', isSafe: false },
    { name: 'Sage', isSafe: false },
    { name: 'Tarragon', isSafe: false },
    { name: 'Marjoram', isSafe: false },
    { name: 'Dill', isSafe: false },
    { name: 'Fennel', isSafe: false },
    { name: 'Lemon Balm', isSafe: false },
    { name: 'Chamomile', isSafe: false },
    { name: 'Lavender', isSafe: false },
    { name: 'Lemon Verbena', isSafe: false },
    { name: 'Bay Leaves', isSafe: false },
    { name: 'Sorbitol', isSafe: false },
    { name: 'Erythritol', isSafe: false },
    { name: 'Mannitol', isSafe: false },
    { name: 'Propylene Glycol', isSafe: false },
    { name: 'Benzoic Acid', isSafe: false },
    { name: 'Sodium Benzoate', isSafe: false },
    { name: 'Potassium Sorbate', isSafe: false },
    { name: 'Calcium Propionate', isSafe: false },
    { name: 'Monosodium Glutamate (MSG)', isSafe: false },
    { name: 'Butylated Hydroxyanisole (BHA)', isSafe: false },
    { name: 'Butylated Hydroxytoluene (BHT)', isSafe: false },
    { name: 'Tert-Butylhydroquinone (TBHQ)', isSafe: false },
    { name: 'Sodium Metabisulfite', isSafe: false },
    { name: 'Calcium Disodium EDTA', isSafe: false },
    { name: 'Sulfur Dioxide', isSafe: false },
    { name: 'Sodium Sulfite', isSafe: false },
    { name: 'Sodium Bisulfite', isSafe: false },
    { name: 'Nitrates', isSafe: false },
    { name: 'Nitrites', isSafe: false },
    { name: 'Titanium Dioxide', isSafe: false },
    { name: 'Artificial Flavor', isSafe: false },
    { name: 'Artificial Color', isSafe: false },
    { name: 'Caramel Color', isSafe: false },
    { name: 'Annatto', isSafe: false },
    { name: 'Allura Red AC', isSafe: false },
    { name: 'Tartrazine', isSafe: false },
    { name: 'Sunset Yellow FCF', isSafe: false },
    { name: 'Brilliant Blue FCF', isSafe: false },
    { name: 'Quinoline Yellow', isSafe: false },
    { name: 'Indigotine', isSafe: false },
    { name: 'Carminic Acid', isSafe: false },
    { name: 'Sodium Erythorbate', isSafe: false },
    { name: 'Azodicarbonamide', isSafe: false },
    { name: 'Dimethylpolysiloxane', isSafe: false },
    { name: 'Sodium Caseinate', isSafe: false },
    { name: 'Hydrolyzed Vegetable Protein', isSafe: false },
    { name: 'Partially Hydrogenated Oil', isSafe: false },
    { name: 'Hydrogenated Oil', isSafe: false },
    { name: 'Carrageenan', isSafe: false },
    { name: 'Polysorbate 80', isSafe: false },
    { name: 'Cellulose Gum', isSafe: false },
    { name: 'Xanthan Gum', isSafe: false },
    { name: 'Guar Gum', isSafe: false },
    { name: 'Locust Bean Gum', isSafe: false },
    { name: 'Maltodextrin', isSafe: false },
    { name: 'High Fructose Corn Syrup', isSafe: false },
    { name: 'Corn Syrup', isSafe: false },
    { name: 'Fructose', isSafe: false },
    { name: 'Sucrose', isSafe: false },
    { name: 'Dextrose', isSafe: false },
    { name: 'Glyceryl Monostearate', isSafe: false },
    { name: 'Calcium Stearate', isSafe: false },
    { name: 'Sodium Stearate', isSafe: false },
    { name: 'Stearic Acid', isSafe: false },
    { name: 'Glycerin', isSafe: false },
    { name: 'Mono- and Diglycerides', isSafe: false },
    { name: 'Sodium Lauryl Sulfate', isSafe: false },
    { name: 'Sodium Laureth Sulfate', isSafe: false },
    { name: 'Polydextrose', isSafe: false },
    { name: 'Sodium Acid Pyrophosphate', isSafe: false },
    { name: 'Triacetin', isSafe: false },
    { name: 'Calcium Chloride', isSafe: false },
    { name: 'Magnesium Sulfate', isSafe: false },
    { name: 'Potassium Chloride', isSafe: false },
    { name: 'Disodium Inosinate', isSafe: false },
    { name: 'Disodium Guanylate', isSafe: false },
    { name: 'Acetylated Distarch Phosphate', isSafe: false },
    { name: 'Sodium Carboxymethyl Cellulose', isSafe: false },
    { name: 'Propylene Glycol Alginate', isSafe: false },
    { name: 'Ethyl Vanillin', isSafe: false },
    { name: 'Vanillin', isSafe: false },
    { name: 'Artificial Sweeteners', isSafe: false },
    { name: 'Aspartame', isSafe: false },
    { name: 'Sucralose', isSafe: false },
    { name: 'Saccharin', isSafe: false },
    { name: 'Acesulfame Potassium', isSafe: false },
    { name: 'Neotame', isSafe: false },
    { name: 'Hydroxyanisole', isSafe: false },
    { name: 'Butylhydroxytoluene', isSafe: false },
    { name: 'Water', isSafe: true },
    { name: 'Rice', isSafe: true },
    { name: 'Oats', isSafe: true },
    { name: 'Barley', isSafe: true },
    { name: 'Quinoa', isSafe: true },
    { name: 'Millet', isSafe: true },
    { name: 'Corn', isSafe: true },
    { name: 'Flaxseed', isSafe: true },
    { name: 'Chia Seeds', isSafe: true },
    { name: 'Pumpkin Seeds', isSafe: true },
    { name: 'Sunflower Oil', isSafe: true },
    { name: 'Fish Oil', isSafe: true },
    { name: 'Olive Oil', isSafe: true },
    { name: 'Coconut Oil', isSafe: true },
    { name: 'Canola Oil', isSafe: true },
    { name: 'Gelatin', isSafe: true },
    { name: 'Peanut Butter', isSafe: true },
    { name: 'Brewer’s Yeast', isSafe: true },
    { name: 'Honey', isSafe: true },
    { name: 'Molasses', isSafe: true },
    { name: 'Carob', isSafe: true },
    { name: 'Turmeric', isSafe: true },
    { name: 'Ginger', isSafe: true },
    { name: 'Parsley', isSafe: true },
    { name: 'Thyme', isSafe: true },
    { name: 'Rosemary', isSafe: true },
    { name: 'Basil', isSafe: true },
    { name: 'Mint', isSafe: true },
    { name: 'Vanilla', isSafe: true },
    { name: 'Carrot Powder', isSafe: true },
    { name: 'Kelp', isSafe: true },
    { name: 'Alfalfa', isSafe: true },
    { name: 'Spinach Powder', isSafe: true },
    { name: 'Spirulina', isSafe: true },
    { name: 'Carrageenan', isSafe: true },
    { name: 'Agar-Agar', isSafe: true },
    { name: 'Pectin', isSafe: true },
    { name: 'Guar Gum', isSafe: true },
    { name: 'Locust Bean Gum', isSafe: true },
    { name: 'Xanthan Gum', isSafe: true },
    { name: 'Beet Pulp', isSafe: true },
    { name: 'Inulin', isSafe: true },
    { name: 'Chicory Root', isSafe: true },
    { name: 'Fructooligosaccharides', isSafe: true },
    { name: 'Lactic Acid', isSafe: true },
    { name: 'Calcium Carbonate', isSafe: true },
    { name: 'Potassium Chloride', isSafe: true },
    { name: 'Sodium Chloride', isSafe: true },
    { name: 'Magnesium Sulfate', isSafe: true },
    { name: 'Zinc Sulfate', isSafe: true },
    { name: 'Iron Sulfate', isSafe: true },
    { name: 'Copper Sulfate', isSafe: true },
    { name: 'Manganese Sulfate', isSafe: true },
    { name: 'Selenium Yeast', isSafe: true },
    { name: 'Choline Chloride', isSafe: true },
    { name: 'Tocopherol', isSafe: true },
    { name: 'Niacin', isSafe: true },
    { name: 'Riboflavin', isSafe: true },
    { name: 'Thiamine Mononitrate', isSafe: true },
    { name: 'Pyridoxine Hydrochloride', isSafe: true },
    { name: 'Vitamin B12 Supplement', isSafe: true },
    { name: 'Folic Acid', isSafe: true },
    { name: 'Biotin', isSafe: true },
    { name: 'Vitamin D3 Supplement', isSafe: true },
    { name: 'Vitamin E Supplement', isSafe: true },
    { name: 'Ascorbic Acid (Vitamin C)', isSafe: true },
    { name: 'Menadione Sodium Bisulfite Complex (Vitamin K)', isSafe: true }
];

      
      
  
    
export const searchFood = (query) => {
    if (!query) return [];
    
    const foodResults = foodData.filter((food) =>
        food.name.toLowerCase().includes(query.toLowerCase())
    );
    
    const ingredientResults = ingredientData.filter((ingredient) =>
        ingredient.name.toLowerCase().includes(query.toLowerCase())
    );
    
    return [...foodResults, ...ingredientResults];
};
