const foodData = [
    { name: 'Apple', isSafe: true},
    { name: 'Banana', isSafe: true},
    { name: 'Blueberries', isSafe: true},
    { name: 'Strawberries', isSafe: true},
    { name: 'Raspberries', isSafe: true},
    { name: 'Blackberries', isSafe: true},
    { name: 'Cantaloupe', isSafe: true},
    { name: 'Watermelon', isSafe: true},
    { name: 'Peaches', isSafe: true},
    { name: 'Pears', isSafe: true},
    { name: 'Pineapple', isSafe: true},
    { name: 'Mango', isSafe: true},
    { name: 'Kiwi', isSafe: true},
    { name: 'Oranges', isSafe: true},
    { name: 'Tangerines', isSafe: true},
    { name: 'Papaya', isSafe: true},
    { name: 'Pumpkin', isSafe: true},
    { name: 'Sweet Potatoes (Cooked)', isSafe: true},
    { name: 'Potatoes (Cooked)', isSafe: true},
    { name: 'Carrots', isSafe: true},
    { name: 'Green Beans', isSafe: true},
    { name: 'Cucumber', isSafe: true},
    { name: 'Zucchini', isSafe: true},
    { name: 'Spinach', isSafe: true},
    { name: 'Kale', isSafe: true},
    { name: 'Broccoli', isSafe: true},
    { name: 'Cauliflower', isSafe: true},
    { name: 'Brussels Sprouts', isSafe: true},
    { name: 'Celery', isSafe: true},
    { name: 'Bell Peppers', isSafe: true},
    { name: 'Peas', isSafe: true},
    { name: 'Lettuce', isSafe: true},
    { name: 'Squash', isSafe: true},
    { name: 'Applesauce (unsweetened)', isSafe: true},
    { name: 'Yogurt (plain)', isSafe: true},
    { name: 'Cottage Cheese (moderate amounts)', isSafe: true},
    { name: 'Cheese (moderate amounts)', isSafe: true},
    { name: 'Eggs', isSafe: true},
    { name: 'Chicken', isSafe: true},
    { name: 'Turkey', isSafe: true},
    { name: 'Beef', isSafe: true},
    { name: 'Lamb', isSafe: true},
    { name: 'Duck', isSafe: true},
    { name: 'Salmon', isSafe: true},
    { name: 'Tuna', isSafe: true},
    { name: 'Trout', isSafe: true},
    { name: 'Whitefish', isSafe: true},
    { name: 'Cod', isSafe: true},
    { name: 'Shrimp', isSafe: true},
    { name: 'Crab', isSafe: true},
    { name: 'Oatmeal', isSafe: true},
    { name: 'Rice', isSafe: true},
    { name: 'Quinoa', isSafe: true},
    { name: 'Barley', isSafe: true},
    { name: 'Pumpkin Seeds', isSafe: true},
    { name: 'Sunflower Seeds', isSafe: true},
    { name: 'Peanut Butter (unsweetened)', isSafe: true},
    { name: 'Almond Butter', isSafe: true},
    { name: 'Cashew Butter', isSafe: true},
    { name: 'Flaxseed', isSafe: true},
    { name: 'Chia Seeds', isSafe: true},
    { name: 'Coconut (unsweetened)', isSafe: true},
    { name: 'Coconut Oil', isSafe: true},
    { name: 'Olive Oil', isSafe: true},
    { name: 'Honey', isSafe: true},
    { name: 'Cranberries', isSafe: true},
    { name: 'Cranberry Sauce (unsweetened)', isSafe: true},
    { name: 'Nectarines', isSafe: true},
    { name: 'Apricots', isSafe: true},
    { name: 'Cherries (pitted)', isSafe: true},
    { name: 'Figs (fresh)', isSafe: true},
    { name: 'Dates (fresh)', isSafe: true},
    { name: 'Persimmons', isSafe: true},
    { name: 'Guava', isSafe: true},
    { name: 'Lychee', isSafe: true},
    { name: 'Dragon Fruit', isSafe: true},
    { name: 'Passion Fruit', isSafe: true},
    { name: 'Pomegranate Seeds', isSafe: true},
    { name: 'Starfruit', isSafe: true},
    { name: 'Durian', isSafe: true},
    { name: 'Jicama', isSafe: true},
    { name: 'Parsnips', isSafe: true},
    { name: 'Turnips', isSafe: true},
    { name: 'Beets', isSafe: true},
    { name: 'Artichokes', isSafe: true},
    { name: 'Asparagus', isSafe: true},
    { name: 'Eggplant', isSafe: true},
    { name: 'Okra', isSafe: true},
    { name: 'Radishes', isSafe: true},
    { name: 'Fennel', isSafe: true},
    { name: 'Water Chestnuts', isSafe: true},
    { name: 'Bok Choy', isSafe: true},
    { name: 'Swiss Chard', isSafe: true},
    { name: 'Arugula', isSafe: true},
    { name: 'Collard Greens', isSafe: true},
    { name: 'Mustard Greens', isSafe: true},
    { name: 'Peaches (fresh)', isSafe: true},
    { name: 'Plums (fresh)', isSafe: true},
    { name: 'Cantaloupe (fresh)', isSafe: true},
    { name: 'Grapefruit', isSafe: true},
    { name: 'Rutabaga', isSafe: true},
    { name: 'Napa Cabbage', isSafe: true},
    { name: 'Butternut Squash', isSafe: true},
    { name: 'Acorn Squash', isSafe: true},
    { name: 'Spaghetti Squash', isSafe: true},
    { name: 'Coconut Meat', isSafe: true},
    { name: 'Mango (fresh)', isSafe: true},
    { name: 'Lychee (fresh)', isSafe: true},
    { name: 'Kumquat', isSafe: true},
    { name: 'Clementine', isSafe: true},
    { name: 'Boysenberries', isSafe: true},
    { name: 'Gooseberries', isSafe: true},
    { name: 'Mulberries', isSafe: true},
    { name: 'Cloudberries', isSafe: true},
    { name: 'Huckleberries', isSafe: true},
    { name: 'Salmonberries', isSafe: true},
    { name: 'Lingonberries', isSafe: true},
    { name: 'Pine Nuts', isSafe: true},
    { name: 'Hemp Seeds', isSafe: true},
    { name: 'Watermelon (seedless)', isSafe: true},
    { name: 'Passionfruit', isSafe: true},
    { name: 'Celeriac', isSafe: true},
    { name: 'Chayote', isSafe: true},
    { name: 'Jackfruit', isSafe: true},
    { name: 'Tamarind', isSafe: true},
    { name: 'Horned Melon', isSafe: true},
    { name: 'Quince', isSafe: true},
    { name: 'Sapodilla', isSafe: true},
    { name: 'Soursop', isSafe: true},
    { name: 'Breadfruit', isSafe: true},
    { name: 'Longan', isSafe: true},
    { name: 'Mung Beans', isSafe: true},
    { name: 'Adzuki Beans', isSafe: true},
    { name: 'Navy Beans', isSafe: true},
    { name: 'Lima Beans', isSafe: true},
    { name: 'Fava Beans', isSafe: true},
    { name: 'Black Beans', isSafe: true},
    { name: 'Kidney Beans', isSafe: true},
    { name: 'Chickpeas', isSafe: true},
    { name: 'Lentils', isSafe: true},
    { name: 'Split Peas', isSafe: true},
    { name: 'Butter Beans', isSafe: true},
    { name: 'Garbanzo Beans', isSafe: true},
    { name: 'Pigeon Peas', isSafe: true},
    { name: 'Cannellini Beans', isSafe: true},
    { name: 'Soybeans', isSafe: true},
    { name: 'Edamame', isSafe: true},
    { name: 'Tempeh', isSafe: true},
    { name: 'Tofu', isSafe: true},
    { name: 'Bamboo Shoots', isSafe: true},
    { name: 'Sprouts', isSafe: true},
    { name: 'Microgreens', isSafe: true},
    { name: 'Alfalfa', isSafe: true},
    { name: 'Cilantro', isSafe: true},
    { name: 'Parsley', isSafe: true},
    { name: 'Basil', isSafe: true},
    { name: 'Mint', isSafe: true},
    { name: 'Thyme', isSafe: true},
    { name: 'Rosemary', isSafe: true},
    { name: 'Oregano', isSafe: true},
    { name: 'Sage', isSafe: true},
    { name: 'Tarragon', isSafe: true},
    { name: 'Dill', isSafe: true},
    { name: 'Chives', isSafe: true},
    { name: 'Garlic (in small amounts)', isSafe: true},
    { name: 'Leeks', isSafe: true},
    { name: 'Shallots', isSafe: true},
    { name: 'Green Onions', isSafe: true},
    { name: 'Beet Greens', isSafe: true},
    { name: 'Turnip Greens', isSafe: true},
    { name: 'Radish Greens', isSafe: true},
    { name: 'Mustard Greens', isSafe: true},
    { name: 'Dandelion Greens', isSafe: true},
    { name: 'Purslane', isSafe: true},
    { name: 'Chicory', isSafe: true},
    { name: 'Endive', isSafe: true},
    { name: 'Frisée', isSafe: true},
    { name: 'Escarole', isSafe: true},
    { name: 'Romaine Lettuce', isSafe: true},
    { name: 'Butter Lettuce', isSafe: true},
    { name: 'Iceberg Lettuce', isSafe: true},
    { name: 'Boston Lettuce', isSafe: true},
    { name: 'Radicchio', isSafe: true},
    { name: 'Sunchokes', isSafe: true},
    { name: 'Taro', isSafe: true},
    { name: 'Yams', isSafe: true},
    { name: 'Jerusalem Artichokes', isSafe: true},
    { name: 'Yucca', isSafe: true},
    { name: 'Jalapeno Peppers', isSafe: true},
    { name: 'Habanero Peppers', isSafe: true},
    { name: 'Poblano Peppers', isSafe: true},
    { name: 'Anaheim Peppers', isSafe: true},
    { name: 'Serrano Peppers', isSafe: true},
    { name: 'Bell Peppers (all colors)', isSafe: true},
    { name: 'Cranberry Beans', isSafe: true},
    { name: 'Pole Beans', isSafe: true},
    { name: 'Snap Beans', isSafe: true},
    { name: 'Runner Beans', isSafe: true},
    { name: 'Soy Beans', isSafe: true},
    { name: 'Broad Beans', isSafe: true},
    { name: 'Scarlet Runner Beans', isSafe: true},
    { name: 'Wax Beans', isSafe: true},
    { name: 'Chinese Long Beans', isSafe: true},
    { name: 'Asparagus Beans', isSafe: true},
    { name: 'Yardlong Beans', isSafe: true},
    { name: 'Lima Beans', isSafe: true},
    { name: 'Fava Beans', isSafe: true},
    { name: 'Pinto Beans', isSafe: true},
    { name: 'Navy Beans', isSafe: true},
    { name: 'Anasazi Beans', isSafe: true},
    { name: 'Black-Eyed Peas', isSafe: true},
    { name: 'Pigeon Peas', isSafe: true},
    { name: 'Yellow Peas', isSafe: true},
    { name: 'Green Peas', isSafe: true},
    { name: 'Split Peas', isSafe: true},
    { name: 'Garbanzo Beans', isSafe: true},
    { name: 'Adzuki Beans', isSafe: true},
    { name: 'Mung Beans', isSafe: true},
    { name: 'Tepary Beans', isSafe: true},
    { name: 'Red Beans', isSafe: true},
    { name: 'White Beans', isSafe: true},
    { name: 'Green Beans', isSafe: true},
    { name: 'Yellow Beans', isSafe: true},
    { name: 'Pink Beans', isSafe: true},
    { name: 'Cranberry Beans', isSafe: true},
    { name: 'Calypso Beans', isSafe: true},
    { name: 'Christmas Lima Beans', isSafe: true},
    { name: 'Italian Flat Beans', isSafe: true},
    { name: 'Dragon Tongue Beans', isSafe: true},
    { name: 'Rattlesnake Beans', isSafe: true},
    { name: 'Tongue of Fire Beans', isSafe: true},
    { name: 'Royal Burgundy Beans', isSafe: true},
    { name: 'Blue Lake Beans', isSafe: true},
    { name: 'Borlotti Beans', isSafe: true},
    { name: 'Cranberry Beans', isSafe: true},
    { name: 'Scarlet Runner Beans', isSafe: true},
    { name: 'Yellow Wax Beans', isSafe: true},
    { name: 'Purple Podded Beans', isSafe: true},
    { name: 'Dragon Langerie Beans', isSafe: true},
    { name: 'Fagiolo di Trasimeno Beans', isSafe: true},
    { name: 'Rodelle di Pratolino Beans', isSafe: true},
    { name: 'Badda Beans', isSafe: true},
    { name: 'Canario Beans', isSafe: true},
    { name: 'Christmas Lima Beans', isSafe: true},
    { name: 'Cannelini Beans', isSafe: true},
    { name: 'Cranberry Beans', isSafe: true},
    { name: 'Boulder Beans', isSafe: true},
    { name: 'Chocolate', isSafe: false},
    { name: 'Grapes', isSafe: false},
    { name: 'Raisins', isSafe: false},
    { name: 'Avocado', isSafe: false},
    { name: 'Onions', isSafe: false},
    { name: 'Garlic', isSafe: false},
    { name: 'Chives', isSafe: false},
    { name: 'Macadamia Nuts', isSafe: false},
    { name: 'Walnuts', isSafe: false},
    { name: 'Pecans', isSafe: false},
    { name: 'Almonds', isSafe: false},
    { name: 'Alcohol', isSafe: false},
    { name: 'Coffee', isSafe: false},
    { name: 'Tea', isSafe: false},
    { name: 'Caffeine', isSafe: false},
    { name: 'Raw Yeast Dough', isSafe: false},
    { name: 'Xylitol (found in sugar-free gum, candies, and baked goods)', isSafe: false},
    { name: 'Salt', isSafe: false},
    { name: 'Fatty Foods', isSafe: false},
    { name: 'Bones (cooked)', isSafe: false},
    { name: 'Corn on the Cob', isSafe: false},
    { name: 'Mushrooms (wild)', isSafe: false},
    { name: 'Nutmeg', isSafe: false},
    { name: 'Raw Eggs', isSafe: false},
    { name: 'Raw Meat', isSafe: false},
    { name: 'Raw Fish', isSafe: false},
    { name: 'Candy', isSafe: false},
    { name: 'Gum', isSafe: false},
    { name: 'Fat Trimmings', isSafe: false},
    { name: 'Spoiled Food', isSafe: false},
    { name: 'Cooked Bones', isSafe: false},
    { name: 'Large Amounts of Dairy Products', isSafe: false},
    { name: 'High-Sodium Foods', isSafe: false},
    { name: 'Sugary Foods', isSafe: false},
    { name: 'Citrus Fruits (large amounts)', isSafe: false},
    { name: 'Apple Seeds', isSafe: false},
    { name: 'Cherry Pits', isSafe: false},
    { name: 'Peach Pits', isSafe: false},
    { name: 'Plum Pits', isSafe: false},
    { name: 'Persimmon Seeds', isSafe: false},
    { name: 'Rhubarb Leaves', isSafe: false},
    { name: 'Tomato Leaves and Stems', isSafe: false},
    { name: 'Potato Leaves and Stems', isSafe: false},
    { name: 'Artificial Sweeteners', isSafe: false},
    { name: 'Blue Cheese', isSafe: false},
    { name: 'Green Tomatoes', isSafe: false},
    { name: 'Unripe Potatoes', isSafe: false},
    { name: 'Wild Cherry', isSafe: false},
    { name: 'Poppy Seeds', isSafe: false},
    { name: 'Mustard Seeds', isSafe: false},
    { name: 'Hops', isSafe: false},
    { name: 'Raw Honey', isSafe: false},
    { name: 'Black Walnuts', isSafe: false},
    { name: 'Stone Fruit Pits', isSafe: false},
    { name: 'Coconut Oil (large amounts)', isSafe: false},
    { name: 'Baking Powder', isSafe: false},
    { name: 'Baking Soda', isSafe: false},
    { name: 'Spices (like garlic powder, onion powder, etc.)', isSafe: false},
    { name: 'Energy Drinks', isSafe: false},
    { name: 'Human Medications', isSafe: false},
    { name: 'Vitamin D Supplements', isSafe: false},
    { name: 'Iron Supplements', isSafe: false},
    { name: 'Pain Relievers (like aspirin, ibuprofen, acetaminophen)', isSafe: false},
    { name: 'Mothballs', isSafe: false},
    { name: 'Detergents', isSafe: false},
    { name: 'Fabric Softener Sheets', isSafe: false},
    { name: 'Antifreeze', isSafe: false},
    { name: 'Rodent Poison', isSafe: false},
    { name: 'Insecticides', isSafe: false},
    { name: 'Weed Killers', isSafe: false},
    { name: 'De-icing Salts', isSafe: false},
    { name: 'Household Cleaners', isSafe: false},
    { name: 'Certain Houseplants', isSafe: false},
    { name: 'Garlic (large amounts)', isSafe: false},
    { name: 'Grapes (fresh and dried)', isSafe: false},
    { name: 'Sugar-Free Candies', isSafe: false},
    { name: 'Marijuana', isSafe: false},
    { name: 'Canned Beans', isSafe: false},
    { name: 'Baked Beans', isSafe: false},
    { name: 'Refried Beans', isSafe: false},
    { name: 'Raw Beans', isSafe: false}
    ];
    
    export const searchFood = (query) => {
        if (!query) return [];
        return foodData.filter((food) =>
            food.name.toLowerCase().includes(query.toLowerCase())
        );
    };
    